/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    PriceDropCover: {
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          inputs: [
            {
              components: [
                {
                  internalType: "contract AggregatorV3Interface",
                  name: "priceFeed",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "triggerDropBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "premiumBps",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "coverPeriod",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "maxPriceAge",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "resolutionGasLimit",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "resolutionFee",
                  type: "uint256",
                },
              ],
              internalType: "struct PriceDropCover.CoverTerms",
              name: "terms",
              type: "tuple",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiry",
              type: "uint256",
            },
          ],
          name: "CoverNotExpired",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "recipient",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "HbarTransferFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "operation",
              type: "string",
            },
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HederaCallFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "requested",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "available",
              type: "uint256",
            },
          ],
          name: "InsufficientFreeCapital",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "requested",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "owned",
              type: "uint256",
            },
          ],
          name: "InsufficientShares",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int256",
              name: "answer",
              type: "int256",
            },
          ],
          name: "InvalidPrice",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidTerms",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "NoRoundFoundBefore",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expiry",
              type: "uint256",
            },
          ],
          name: "NoScheduleCapacity",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "holder",
              type: "address",
            },
          ],
          name: "NotPolicyHolder",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "NothingToClaim",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "PolicyNotActive",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "PolicyTokenAlreadyCreated",
          type: "error",
        },
        {
          inputs: [],
          name: "PolicyTokenNotCreated",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              internalType: "uint256",
              name: "timestamp",
              type: "uint256",
            },
          ],
          name: "RoundNotLastBefore",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "updatedAt",
              type: "uint256",
            },
          ],
          name: "StalePrice",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "remainingShares",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minShares",
              type: "uint256",
            },
          ],
          name: "TooFewSharesBackPolicies",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "voidableAt",
              type: "uint256",
            },
          ],
          name: "VoidTooEarly",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minAmount",
              type: "uint256",
            },
          ],
          name: "WithdrawalBelowMinimum",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "expected",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "received",
              type: "uint256",
            },
          ],
          name: "WrongPayment",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroAmount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "ZeroShares",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "holder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "premium",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "strikePrice",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiry",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "resolutionSchedule",
              type: "address",
            },
          ],
          name: "CoverBought",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "underwriter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
          ],
          name: "Deposited",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "holder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PayoutClaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "holder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "PayoutUnclaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "enum PriceDropCover.PolicyStatus",
              name: "outcome",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
            {
              indexed: false,
              internalType: "int256",
              name: "priceAtExpiry",
              type: "int256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "holder",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amountPaid",
              type: "uint256",
            },
          ],
          name: "PolicyResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "PolicyTokenCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "underwriter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "MIN_SHARES_BACKING_POLICIES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "UNRESOLVED_VOID_DELAY",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "VIRTUAL_SHARES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "underwriter",
              type: "address",
            },
          ],
          name: "assetsOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
          ],
          name: "buyCover",
          outputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "claimPayout",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "coverPeriod",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "createPolicyToken",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "deposit",
          outputs: [
            {
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "freeCapital",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "lockedCapital",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "maxPriceAge",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "policies",
          outputs: [
            {
              internalType: "uint128",
              name: "payout",
              type: "uint128",
            },
            {
              internalType: "uint128",
              name: "premium",
              type: "uint128",
            },
            {
              internalType: "int256",
              name: "strikePrice",
              type: "int256",
            },
            {
              internalType: "uint64",
              name: "expiry",
              type: "uint64",
            },
            {
              internalType: "enum PriceDropCover.PolicyStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "resolutionSchedule",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "policyToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premiumBps",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
          ],
          name: "previewRedeem",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "priceFeed",
          outputs: [
            {
              internalType: "contract AggregatorV3Interface",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
          ],
          name: "quote",
          outputs: [
            {
              internalType: "uint256",
              name: "premium",
              type: "uint256",
            },
            {
              internalType: "int256",
              name: "strikePrice",
              type: "int256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "reservedResolutionFees",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "resolutionFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "resolutionGasLimit",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "resolve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
            {
              internalType: "uint80",
              name: "roundId",
              type: "uint80",
            },
          ],
          name: "resolveWithRound",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "underwriter",
              type: "address",
            },
          ],
          name: "sharesOf",
          outputs: [
            {
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "sharesToWithdraw",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalAssets",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalShares",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "triggerDropBps",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "unclaimedPayoutOf",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "unclaimedPayouts",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "policyId",
              type: "uint256",
            },
          ],
          name: "voidUnresolved",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minAmount",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
